name: Build Go Binary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Windows AMD64
      run: |
        GOOS=windows GOARCH=amd64 go build -o colo-windows-amd64.exe colo.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: colo-windows-amd64
        path: colo-windows-amd64.exe
